# This file is an example of inputs that will be passed to configure.py,
# annotated to say which fields are required for what purposes.
# Note that the attribute *keys* must have the names here but the
# *values* can be changed depending on where the relevant information is
# in your input files.
#
# The first top-level entry is a listing of all the fields
# that the catalogs can be assigned to.  Here are a few
Fields:
- name:  0640-34
  coords:    06:40:00  -34:00:00
  radius: 2.
- name:  0730-50
  coords:    07:30:00 -50:00:00
  radius: 2.
#
# Next section indicates the sources for all
# input catalogs, and how to assign EXPOSURE names
# to each one
Files:
- glob: CATS/D00*.cat
# This entry catches all of the DECam exposures
# and gives them EXPOSURE values like "D228325"
  expkey: < EXPNUM
  translation: '(.*)=D\1'
# Now lets get the Gaia reference catalogs for these fields,
# and explicitly assign them EXPOSURE values:
- glob:  /data3/DECAM/PHOTCAL/STARFLATS/ASTREF/gaia.0640-34.cat
  expkey: gaia0640
- glob:  /data3/DECAM/PHOTCAL/STARFLATS/ASTREF/gaia.0730-50.cat
  expkey: gaia0730
#
# Now the bulk of the file goes to specifying attributes to
# be attached to each catalog extension or exposure.
#
Attributes:
#
# Which instrument configuration does the exposure use? (Required;
# must match across devices of exposure)
- key:    INSTRUMENT
  value:  < FILTER
  translation: '^\s*(.).*$=\1'
#
# What photometric band are the data taken in? (Required;
# must match across devices of exposure)
- key:    BAND
  value:  < FILTER
  translation: '^\s*(.).*$=\1'
#
# What field name is this exposure in?  Here just choose nearest field
# based on RA/DEC. (Required; must match across devices of exposure)
- key:    FIELD
  value:  _NEAREST
#
# What device were detections in this catalog made from (Required)
- key:    DEVICE
  value:  < DETPOS
#
# RA and DEC of telescope axis or field center.  (Required, though maybe not
# for reference catalogs unless you use FIELD=_NEAREST.  Must match across devices
# for a given exposure)
- key:    RA
  value:  < TELRA
- key:    DEC
  value:  < TELDEC
#
# Specify the starting WCS for this extension.  Here, as will be typical, it
# is to be read from the catalog header as a FITS WCS. (Required)
- key:    WCSIN
  value:  _HEADER
#
# Which columns of the table contain the x and y pixel positions of the detections? (Reqd)
- key:    XKEY
  value:  XWIN_IMAGE
- key:    YKEY
  value:  YWIN_IMAGE
#
# Which column of table contains id string for detections?  Here just using row number
# in the table. (Required but unimportant)
- key:    IDKEY
  value:  _ROW
#
# What Boolean function of the detection table's values is used to determine whether
# a detection should be used in the fitting process?  (Required, but value could just be
# set to null string '' to accept entire catalog)
- key:    SELECT
  value:  >
    ERRAWIN_IMAGE<0.05 && 
    XWIN_IMAGE>20 && YWIN_IMAGE>10 && 
    XWIN_IMAGE<2029 && YWIN_IMAGE<4087 && 
    MAGERR_AUTO<0.03 &&
    (IMAFLAGS_ISO & 4095) ==0 &&
    (FLAGS & 231) ==0
# What Boolean function of the detection table's values is used to determine whether
# a detection is a star vs a galaxy? (Required, but value could just be set to null string
# '' to consider everything a star)
- key:    STARSELECT
  value:  SPREAD_MODEL > -0.003 && SPREAD_MODEL < 0.003
#
# Affinity says that galaxies in this catalog are only allowed to match galaxies with
# the same affinity.  Here allowing only detections in common BAND to match.
- key:    AFFINITY
  value:  '${BAND}'
#
# Which column holds the uncertainty in x & y pixel positions? (Required only for WCSFit)
- key:    ERRKEY
  value:  ERRAWIN_IMAGE
#
# Relative weight for detection in this exposure during astrometric fits (Required only for WCSFit)
- key:    WEIGHT
  vtype:  float
  value:  1.
#
# Airmass to use in forcing exposure zeropoints to conform to nightly formulae (Required
# only if using airmass terms in PhotoFit)
- key:    AIRMASS
  vtype:  float
  value:  < AIRMASS
#
# Exposure time used to adjust tabulated magnitudes by +2.5*log10(exptime) (Required for PhotoFit)
- key:    EXPTIME
  vtype:  float
  value:  < EXPTIME
#
# Modified Julian date - not really used for anything yet.
- key:    MJD
  vtype:  float
  value:  < MJD-OBS
#
# Columns holding magnitude to use for photometry fitting, and its uncertainty.  Notation
# here indicates using (zero-indexed) element #7 in the MAG_APER vector. (Required for
# PhotoFit.  MAGERRKEY also used for S/N cuts)
- key:    MAGKEY
  value:  MAG_APER[7]
- key:    MAGERRKEY
  value:  MAGERR_APER[7]
#
# Weight to apply to detections in this catalog during photometric fitting (Required for PhotoFit)
- key:    MAGWEIGHT
  vtype:  float
  value:  1.
#
# Aperture correction used in forcing zeropoints to conform to nightly formulae (Required only
# if using apcorr term in photometric prior for PhotoFit)
- key:    APCORR
  vtype:  float
  value:  <APCOR09
  default: 0.
#
# Hour angle (Currently used only by auxiliary program that calculates parallactic angle and
# airmass)
- key: HA
  vtype:  str
  value:   < HA
  default: "00:00:00"
#
# Below are some attributes having "select" entries that specify they are to be applied only
# to our Gaia astrometric reference catalogs.  Note that all of these occur *after* the
# generic entries above, because later entries have priority, and we want these entries to
# override the generic definitions in the cases where the selection matches.
#
# The Gaia catalogs are from the special "reference" instrument and band.
- key:  INSTRUMENT
  select: gaia.*
  value: _REFERENCE
- key:  BAND
  select: gaia.*
  value: _REFERENCE
#
# Gaia catalog is already in ICRS RA/Dec.
- key:  WCSIN
  select: gaia.*
  value: _ICRS
- key:  WEIGHT
  select: gaia.*
  vtype: float
  value: 1.
#
# Gaia objects are all known to be STELLAR and astrometric match to all bands
- key:  AFFINITY
  select: gaia.*
  value: STELLAR
- key:  XKEY
  select: gaia.*
  value: RA_ICRS
- key:  YKEY
  select: gaia.*
  value: DE_ICRS
- key:  ERRKEY
  select: gaia.*
  value: e_RA_ICRS
- key:  SELECT
  select: gaia.*
  value: e_RA_ICRS < 0.02/3600.
- key:  STARSELECT
  select: gaia.*
  value: ''
- key:  MAGKEY
  select: gaia.*
  value: MAG
- key:  MAGERRKEY
  select: gaia.*
  value: MAGERR
- key:  DEVICE
  select: gaia.*
  value:  gaia
#
# Give coordinates of specific catalogs (or could give FIELD)
- key:  RA
  select:  gaia0640
  value: '06:40:00'
- key:  DEC
  select:  gaia0640
  value: '-34:00:00'
